#### Audio Classification Data Preprocessing

In [1]:
from google.colab import drive

ModuleNotFoundError: No module named 'google'

In [2]:
drive.mount('/content/drive')

NameError: name 'drive' is not defined

In [3]:
!pip install jovian --upgrade

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import jovian
!pip install librosa

Defaulting to user installation because normal site-packages is not writeable


In [5]:
### Let's read a sample audio using librosa
import librosa
audio_file_path='/content/drive/MyDrive/Audio-Classification-main/prit.wav'
# audio_file_path='/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/audio/fold10/115418-9-0-11.wav'
librosa_audio_data,librosa_sample_rate=librosa.load(audio_file_path)

C:\ProgramData\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [6]:
print(librosa_audio_data)

NameError: name 'librosa_audio_data' is not defined

In [7]:
### Lets plot the librosa audio data
import matplotlib.pyplot as plt
# Original audio with 1 channel
plt.figure(figsize=(12, 4))
plt.plot(librosa_audio_data)

NameError: name 'librosa_audio_data' is not defined

<Figure size 1200x400 with 0 Axes>

#### Observation
Here Librosa converts the signal to mono, meaning the channel will alays be 1

In [8]:
### Lets read with scipy
from scipy.io import wavfile as wav
wave_sample_rate, wave_audio = wav.read(audio_file_path)

NameError: name 'audio_file_path' is not defined

In [9]:
wave_audio

NameError: name 'wave_audio' is not defined

In [10]:
import matplotlib.pyplot as plt

# Original audio with 2 channels
plt.figure(figsize=(12, 4))
plt.plot(wave_audio)

NameError: name 'wave_audio' is not defined

<Figure size 1200x400 with 0 Axes>

### Extract Features
Here we will be using Mel-Frequency Cepstral Coefficients(MFCC) from the audio
samples.
The MFCC summarises the frequency distribution across the window size, so it is possible to analyse both the frequency and time characteristics of the sound. These audio representations will allow us to identify features for classification.

In [11]:
mfccs = librosa.feature.mfcc(y=librosa_audio_data, sr=librosa_sample_rate, n_mfcc=40)
print(mfccs.shape)

NameError: name 'librosa' is not defined

In [12]:
mfccs

NameError: name 'mfccs' is not defined

In [46]:
import librosa

# Load an audio file
audio_file = '/content/drive/MyDrive/Audio-Classification-main/prit.wav'
y, sr = librosa.load(audio_file, sr=None)  # Use sr=None to preserve the original sample rate

# 'sr' contains the sample rate of the loaded audio
print("Sample rate:", sr)


Sample rate: 48000


In [44]:
import wave

# Open the audio file
audio_file = '/content/drive/MyDrive/Audio-Classification-main/prit.wav'
with wave.open(audio_file, 'rb') as wf:
    sr = wf.getframerate()

# 'sr' contains the sample rate of the audio file
print("Sample rate:", sr)


Sample rate: 48000


In [14]:
#### Extracting MFCC's For every audio file
import pandas as pd
import os
import librosa

# audio_dataset_path='/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/audio'
# metadata=pd.read_csv('/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/metadata/UrbanSound8K.csv')

audio_dataset_path='UrbanSound8K/audio/man'
metadata=pd.read_csv('UrbanSound8K/metadata/man.csv')
metadata.head()

AttributeError: module 'numpy' has no attribute 'complex'.
`np.complex` was a deprecated alias for the builtin `complex`. To avoid this error in existing code, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [31]:
!pip install llvmlite
!pip install resampy

In [157]:
import librosa
import wave
# Load an audio file
audio_file = '/content/drive/MyDrive/Audio-Classification-main/prit.wav'
y, sr = librosa.load(audio_file, sr=None)  # Use sr=None to keep the original sample rate
with wave.open(audio_file, 'rb') as wf:
    sr = wf.getframerate()
mfccs_features = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=40)


print(mfccs_features)
# Resample the audio to the desired sample rate
# target_sr = 22050  # Your desired sample rate
# y_resampled = librosa.resample(y, sr, target_sr)

# Now 'y_resampled' contains the audio resampled to the desired sample rate


[[-6.9204285e+02 -6.8484302e+02 -6.7976819e+02 ... -6.7250928e+02
  -6.6393134e+02 -6.7084210e+02]
 [ 6.5902615e+00  1.0918627e+01  1.4685146e+01 ...  2.6004814e+01
   3.5720703e+01  2.7662577e+01]
 [ 1.1220558e+00 -3.6262894e+00 -4.7271528e+00 ...  4.5202422e+00
   8.7367773e+00  5.6206913e+00]
 ...
 [-6.4608061e-01 -9.7876322e-01  1.3122840e+00 ...  1.5812027e-01
   2.0590958e-01  3.7262039e+00]
 [-2.6055024e+00 -3.9833980e+00  2.1248102e+00 ...  6.1505634e-01
  -5.8068120e-01  3.3003516e+00]
 [-3.0171866e+00 -2.9083254e+00  5.4122329e+00 ...  2.4038069e+00
  -2.7060968e-01  2.5304222e+00]]


In [158]:
def features_extractor(file):
  with wave.open(file_name, 'rb') as wf:
    sr2 = wf.getframerate()
    audio, sample_rate = librosa.load(file_name, res_type=None)
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sr2, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)

    return mfccs_scaled_features


In [159]:
def features_extractor(file):
    # audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
    audio, sample_rate = librosa.load(file_name)
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)

    return mfccs_scaled_features

import numpy as np
import resampy as rs
from tqdm import tqdm
### Now we iterate through every audio file and extract features
### using Mel-Frequency Cepstral Coefficients
extracted_features=[]
for index_num,row in tqdm(metadata.iterrows()):
    file_name = os.path.join(os.path.abspath(audio_dataset_path),'fold'+str(row["fold"])+'/',str(row["slice_file_name"]))
    final_class_labels=row["class"]
    data=features_extractor(file_name)
    extracted_features.append([data,final_class_labels])

22it [00:05,  3.80it/s]


In [160]:
### converting extracted_features to Pandas dataframe
extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df.head()

feature        class
0  [-447.12952, 105.81826, 23.667995, 14.22423, 1...  Prit Chavda
1  [-445.97934, 93.10476, 23.450607, 10.971537, 9...  Prit Chavda
2  [-443.8292, 84.861404, 19.81303, 11.040088, 7....  Prit Chavda
3  [-421.24622, 117.20875, 25.92727, 14.127257, 1...  Prit Chavda
4  [-455.1913, 111.417725, 29.266699, 21.61553, 1...  Prit Chavda

In [161]:
### Split the dataset into independent and dependent dataset
X=np.array(extracted_features_df['feature'].tolist())
y=np.array(extracted_features_df['class'].tolist())

In [163]:
X.shape

(22, 40)

In [162]:
y

array(['Prit Chavda', 'Prit Chavda', 'Prit Chavda', 'Prit Chavda',
       'Prit Chavda', 'Prit Chavda', 'Prit Chavda', 'Prit Chavda',
       'Prit Chavda', 'Prit Chavda', 'Dhruv Chavda', 'Dhruv Chavda',
       'Dhruv Chavda', 'Dhruv Chavda', 'Dhruv Chavda', 'Dhruv Chavda',
       'Dhruv Chavda', 'Dhruv Chavda', 'Dhruv Chavda', 'Dhruv Chavda',
       'Dhruv Chavda', 'Dhruv Chavda'], dtype='<U12')

In [164]:
### Label Encoding
###y=np.array(pd.get_dummies(y))
### Label Encoder
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
y=to_categorical(labelencoder.fit_transform(y))

In [165]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [166]:
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [167]:
X_train

array([[-5.32244019e+02,  6.91069107e+01,  1.34922438e+01,
         2.87528515e+00,  4.37864065e+00, -3.46143484e+00,
        -8.91626453e+00, -8.20732975e+00, -5.69006443e+00,
        -4.09218121e+00, -2.15526819e-01,  4.38846588e+00,
        -9.17981118e-02, -7.42832661e+00, -6.45684481e+00,
        -6.45547819e+00, -1.00180063e+01, -8.37133980e+00,
        -5.20784140e+00, -4.06639576e+00, -1.69498169e+00,
        -1.67801484e-01, -1.12177122e+00, -1.91623819e+00,
        -1.56099784e+00, -2.78153002e-01, -6.98252201e-01,
        -3.52627945e+00, -3.95191646e+00, -1.53356862e+00,
        -8.75729799e-01, -3.06259894e+00, -5.13537407e+00,
        -4.47904730e+00, -2.44545364e+00, -2.77881455e+00,
        -3.84936404e+00, -2.24262500e+00, -1.14926553e+00,
        -2.60199261e+00],
       [-4.59850006e+02,  5.76471443e+01,  1.71161938e+01,
         4.42281866e+00,  6.26123607e-01, -6.16398144e+00,
        -9.48344994e+00, -1.01337271e+01, -8.50407505e+00,
        -6.14669228e+00, -2.51

In [168]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [169]:
X_train.shape

(17, 40)

In [170]:
X_test.shape

(5, 40)

In [171]:
y_train.shape

(17, 2)

In [172]:
y_test.shape

(5, 2)

### Model Creation

In [173]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [174]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [175]:
### No of classes
num_labels=y.shape[1]

In [176]:
model=Sequential()
###first layer
model.add(Dense(100,input_shape=(40,)))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###second layer
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.5))
###third layer
model.add(Dense(100))
model.add(Activation('relu'))
model.add(Dropout(0.5))

###final layer
model.add(Dense(num_labels))
model.add(Activation('softmax'))

In [177]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 100)               4100      
                                                                 
 activation_4 (Activation)   (None, 100)               0         
                                                                 
 dropout_3 (Dropout)         (None, 100)               0         
                                                                 
 dense_5 (Dense)             (None, 200)               20200     
                                                                 
 activation_5 (Activation)   (None, 200)               0         
                                                                 
 dropout_4 (Dropout)         (None, 200)               0         
                                                                 
 dense_6 (Dense)             (None, 100)              

In [178]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [179]:
## Trianing my model
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime

num_epochs = 100
num_batch_size = 32

# checkpointer = ModelCheckpoint(filepath='saved_models/audio_classification.hdf5',
checkpointer = ModelCheckpoint(filepath='/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/saved_models/audio_classification.hdf5',
                               verbose=1, save_best_only=True)
start = datetime.now()

model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)


duration = datetime.now() - start
print("Training completed in time: ", duration)

Epoch 1/100
1/1 [==============================] - ETA: 0s - loss: 27.0596 - accuracy: 0.4706
Epoch 1: val_loss improved from inf to 3.34810, saving model to /content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/saved_models/audio_classification.hdf5
1/1 [==============================] - 1s 1s/step - loss: 27.0596 - accuracy: 0.4706 - val_loss: 3.3481 - val_accuracy: 0.2000
Epoch 2/100
1/1 [==============================] - ETA: 0s - loss: 24.8395 - accuracy: 0.5294
Epoch 2: val_loss did not improve from 3.34810
1/1 [==============================] - 0s 49ms/step - loss: 24.8395 - accuracy: 0.5294 - val_loss: 9.0135 - val_accuracy: 0.2000
Epoch 3/100
1/1 [==============================] - ETA: 0s - loss: 33.3451 - accuracy: 0.4706
Epoch 3: val_loss did not improve from 3.34810
1/1 [==============================] - 0s 76ms/step - loss: 33.3451 - accuracy: 0.4706 - val_loss: 11.3243 - val_accuracy: 0.2000
Epoch 4/100
1/1 [==============================] - ETA: 0s - loss: 56.302

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(



Epoch 4: val_loss did not improve from 3.34810
1/1 [==============================] - 0s 46ms/step - loss: 56.3022 - accuracy: 0.3529 - val_loss: 12.5974 - val_accuracy: 0.2000
Epoch 5/100
1/1 [==============================] - ETA: 0s - loss: 23.4480 - accuracy: 0.6471
Epoch 5: val_loss did not improve from 3.34810
1/1 [==============================] - 0s 44ms/step - loss: 23.4480 - accuracy: 0.6471 - val_loss: 12.6265 - val_accuracy: 0.2000
Epoch 6/100
1/1 [==============================] - ETA: 0s - loss: 31.1563 - accuracy: 0.5882
Epoch 6: val_loss did not improve from 3.34810
1/1 [==============================] - 0s 66ms/step - loss: 31.1563 - accuracy: 0.5882 - val_loss: 10.0299 - val_accuracy: 0.2000
Epoch 7/100
1/1 [==============================] - ETA: 0s - loss: 19.9720 - accuracy: 0.5294
Epoch 7: val_loss did not improve from 3.34810
1/1 [==============================] - 0s 63ms/step - loss: 19.9720 - accuracy: 0.5294 - val_loss: 9.1243 - val_accuracy: 0.2000
Epoch 8/10

In [180]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])

1.0


In [97]:
import numpy as np
from tensorflow.keras.models import load_model

# Load your pre-trained model
model = load_model("/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/saved_models/audio_classification.hdf5")  # Replace with your model file path

# Define the filename
filename = "/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/audio/fold2/33849-3-4-0.wav"

# Extract audio features (replace this with your actual feature extraction function)
# def features_extractor(filename):
    # Your feature extraction code here
    # This function should return a feature vector

# Extract features from the audio file
prediction_feature = features_extractor(filename)
prediction_feature = np.array(prediction_feature).reshape(1, -1)  # Reshape the feature vector

# Make predictions using the loaded model
predicted_class = model.predict_classes(prediction_feature)

print("Predicted Class:", predicted_class)


AttributeError: ignored

In [101]:
filename= "/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/audio/fold2/33849-3-4-0.wav"
prediction_feature=features_extractor(filename)
prediction_feature=prediction_feature.reshape(1,-1)
# model.predict_classes(prediction_feature)
predict_x=model.predict(prediction_feature)
classes_x=np.argmax(predict_x,axis=1)

# predictions = (model.predict(prediction_feature) > 0.5).astype("int32")
# print(model.Object)

ValueError: ignored

In [181]:
prediction_feature.shape

(13, 120)

In [182]:
X_test[1]

array([-4.5314615e+02,  5.4559879e+01,  1.3782588e+01,  1.9541658e+00,
       -1.2050936e+00, -5.9753385e+00, -9.5100908e+00, -1.0058624e+01,
       -8.5193729e+00, -5.4231167e+00, -1.8066807e-01,  3.1218708e+00,
       -1.0456554e+00, -6.7667394e+00, -6.8110752e+00, -8.5952673e+00,
       -1.1634469e+01, -8.4895782e+00, -3.3697767e+00, -1.6780357e+00,
       -1.8822579e+00, -2.0942943e+00, -2.0602691e+00, -3.0962268e-01,
        7.0542222e-01, -1.0098896e+00, -3.8269055e+00, -4.9201202e+00,
       -1.8283931e+00, -2.9463025e-02, -2.7216721e+00, -4.3104019e+00,
       -3.0383835e+00, -3.0099015e+00, -4.5529213e+00, -4.2602773e+00,
       -3.2452562e+00, -3.6567042e+00, -3.7311511e+00, -1.4649446e+00],
      dtype=float32)

In [201]:
# model.predict_classes(X_test)
predict_x=model.predict(X_test)
classes_x=np.argmax(predict_x,axis=1)

1/1 [==============================] - 0s 34ms/step


### Testing Some Test Audio Data

Steps
- Preprocess the new audio data
- predict the classes
- Invere transform your Predicted Label

In [204]:
# filename="/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/audio/man/fold2/dhruv1.wav"
filename="/content/drive/MyDrive/Audio-Classification-main/UrbanSound8K/audio/som.wav"

import wave
# Load an audio file
y, sr = librosa.load(audio_file, sr=None)  # Use sr=None to keep the original sample rate
with wave.open(filename, 'rb') as wf:
    sr = wf.getframerate()


audio, sample_rate = librosa.load(filename)
mfccs_features = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
mfccs_scaled_features = np.mean(mfccs_features.T,axis=0)

# print(mfccs_scaled_features)
mfccs_scaled_features=mfccs_scaled_features.reshape(1,-1)
# print(mfccs_scaled_features)
# print(mfccs_scaled_features.shape)
# predicted_label=model.predict_classes(mfccs_scaled_features)
print(predicted_label)
predictions = (model.predict(mfccs_scaled_features) > 0.5).astype("int32")
predictionss = -1;
value = 0;
for x in predictions:
  for y in x:
    # print(y , "\n")
    predictionss+=1
    if y==1 :
      value = 1;
      break

# predictions = [0 0 0 1 0 0 0 0 0 0]
if value == 1:
  print(predictions)
  print([predictionss])
  prediction_class = labelencoder.inverse_transform([predictionss])
  print(prediction_class)
else:
  print("not maching any one");

[5 4 4 ... 1 2 3]
1/1 [==============================] - 0s 43ms/step
[[1 0]]
[0]
['Dhruv Chavda']
